### ISSUE TITLE
Annotation protocol for genes and transcripts

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#11]
Annotate protocol for the following terms:

- Describe source of annotation RefSeq and how to add it
- Describe source of annotation Ensembl and how to add it
- Annotate each capture_kit target file with refseq gene names and exon number

**Comment by hassanfa** [comment]
@vwirta This is the first issue we have in this repository regarding annotating gene panels. This is couple of months old, but there are other issues in this repo that you should look into or add if you think they are missing. You might also want to add it to your watch list to keep the progress.

**Comment by vwirta** [comment]
@hassanfa thanks for the update!
I have missed this repo :) now watching!

**Comment by hassanfa** [comment]
@keyvanelhami this is the project you are working on. Adding it to Cg back log. Can you please create a post it note and add it to the wall on BALSAMIC lane?

**Comment by keyvanelhami** [comment]
> @keyvanelhami this is the project you are working on. Adding it to Cg back log. Can you please create a post it note and add it to the wall on BALSAMIC lane?

Yeah sure, I will create a Post-it. Should I start with with creating a pull-request too so @annaengstrom can test the new script?

**Comment by hassanfa** [comment]
Two issues are independent from each other. But outputs are for final annotation of bedfiles.

This one being more important than the other, it would be nice to finish this first.

**Comment by keyvanelhami** [comment]
@emiliaol @henrikstranneheim I talked to Patrik to put a post-it on the board. He told me to contact you. What are the routines?

**Comment by hassanfa** [comment]
Keyvan, I've talked to Henrik about this before. This is a fairly long project, and it is nice to notify others what is being worked on. IMO it is ok to put a post-it up, you've been working on this for 2-3weeks :-)

**Comment by keyvanelhami** [comment]
@henrikstranneheim I am unable to add any "gain" or "effort" labels. Do you know why? I can't find these label.
