### ISSUE TITLE
Add PoN for GMCKSolid

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#26]
(Adding ideas from comments to issue):

- PoN for FFPE
- PoN for FF
- PoN based on gender
- PoN for CNV analysis

**Comment by vwirta** [comment]
We should consider having multiple PoNs for certain designs.
For example, one for FFPE samples and one for FF samples

**Comment by hassanfa** [comment]
Will add these to small reference repo instead.
