### ISSUE TITLE
On the bedfiles and how to handle them

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#28]
Hello @henrikstranneheim @patrikgrenfeldt ,

Also tagging @annaengstrom and @emiliaol to keep them in the loop.

First of all, there were some confusion on "shasum" of these bed files, and the reason for difference for "shasum" was the inclusion of "track-line" and "chr" in bedfiles on the github repo. While on the bedfiles for analysis don't have those.

Secondly, I think you have already seen the new changes in cg/clinical-db that @patrikgrenfeldt addressed. It is related to this issue on cg: https://github.com/Clinical-Genomics/cg/issues/358 and this github repo I started sometime ago. The idea is to have unique names for each target bed panel in the order portal so customers can use that while they are ordering, and we use that exact bed file in the analysis. Then there is version of each panel that Patrick already thought of it and added to clinical-db.

Now here comes the challenge of providing these bedfiles to analysis. Balsamic requires a bed file path, I assume MIP does the same, @henrikstranneheim ?

If MIP can handle a path for bedfile via CLI/config and take care of small panels (missing contigs and whatnot), then Patrick's solution is way to go as it is a superior solution than to dump this task on workflows.

Here are the todo list that needs to be done in order to make Patrick's solution work asap :
- [x] Create bedfile suitable for workflows on this repo ( @henrikstranneheim is it ok if you and I decide this?)
- [x] Define naming convention for each bedfile on this repo (@annaengstrom and @hassanfa )
- [x] Define a unique name/tag (other than bed filename) for each panel on this repo (@patrikgrenfeldt @annaengstrom  is it ok if you guys can decide this together?)
- [x] Upload information for these bedfiles to clinical-db (@annaengstrom can you please take care of this?)
- [x] Make sure workflows' and cg's needs are satisfied for each bedfile (this should solve itself as we finish above four items).

Any thoughts?

**Comment by henrikstranneheim** [comment]
**Now here comes the challenge of providing these bedfiles to analysis. Balsamic requires a bed file path, I assume MIP does the same, @henrikstranneheim ?**

Yes, you can supply it on the CLI or in the config - this is for any capture bed file. You can also supply an akronym in the pedigree per sample and MIP will use the corresponding bed file (these are a limited set of supported ones).
 
**If MIP can handle a path for bedfile via CLI/config and take care of small panels (missing contigs and whatnot),**

We use the exclude_contigs option to do this (also on CLI or config). However, MIP will default to always use the contigs supplied in the gene_panels.bed, but we can deal with the details later. 

**Create bedfile suitable for workflows on this repo ( @henrikstranneheim is it ok if you and I decide this?)**
Sure no problem!

**Any thoughts?**

Nice summary and it will be great to have a unified handling on capture bed files. This also relates to this: https://github.com/Clinical-Genomics/servers/pull/252. Where we need to put logic in cg on which MIP config/CLI to use depending on size of panel etc.

**Comment by annaengstrom** [comment]
Sound like a good plan! I will discuss further with @patrikgrenfeldt and you @hassanfa. And yes, I can do the uploading to clinical-db.

**Comment by emiliaol** [comment]
To clarify we only need to make sure cg adds the "Filename" to `capture_kit` in the pedigree for MIP analysis starts. And then make sure the bed file is available with the corresponding file name in `/home/proj/production/rare-disease/references/references_*/`. That was MIP doesn't have to know how to translate any of the names of the capture panels

**Comment by hassanfa** [comment]
@emiliaol 

The goal of this repository is to provide annotation, meta data, and to keep changes in target bed files in check for Cancer panels. The bed files created here are following UCSC bed file format guidelines: https://genome.ucsc.edu/FAQ/FAQformat#format1 (3-column format with bed track).

Now, this has nothing to do with `/home/proj/production/rare-disease/references/references_*/` (maybe a little), that is a workflow and cg internal issue. Workflows (balsamic and mip) have to take these bed files, and prepare them the way it is suitable. That's the reason I created the first bullet point above 😉: 

> Create bedfile suitable for workflows on this repo ( henrikstranneheim is it ok if you and I decide this?)

Hope this helps.

**Comment by hassanfa** [comment]
@vwirta too many tags I knows, but also this issue on my attempt to harmonize panels  😄 . I am still confused why would MIP need small panels (since rare diseases go on WGS anyway), but why not.

**Comment by vwirta** [comment]
> I am still confused why would MIP need small panels (since rare diseases go on WGS anyway), but why not.

Some rare disease cases will be analysed using panels (exoms or even smaller panels such as GMCK Solid) because the referring clinic does not want to take the cost of WGS. We have some patient categories where this will be standard, eg cardio and hearing loss.

**Comment by AnnaLeinfelt** [comment]
Also touched upon i AM suggestion for improvement, FF113. 
I will set a reminder there to follow up later in 2020.

**Comment by annaengstrom** [comment]
@hassanfa and I have completed the name convention [here](https://github.com/Clinical-Genomics/target_capture_bed#versioning-schema).

**Comment by hassanfa** [comment]
Link takes to this repository's main page. Is that correct?

**Comment by hassanfa** [comment]
Final step is to update status-db https://github.com/Clinical-Genomics/cg/issues/535 , AM docs, and that's it!

**Comment by annaengstrom** [comment]
Clinical-Genomics/cg#535 is done but I think we need to do Clinical-Genomics/cg#558 before we can close this issue, do you agree?

**Comment by hassanfa** [comment]
Yes, afaik last step is mostly done or done. There were couple of PRs in CG for it.

**Comment by annaengstrom** [comment]
@henrikstranneheim can I close this issue?

**Comment by hassanfa** [comment]
@annaengstrom How about the names here: https://clinical-api.scilifelab.se/admin/bed/ ?

**Comment by annaengstrom** [comment]
These are the names that the customers use for the actual order, these terms are available here: https://clinical.scilifelab.se/requirements and are "approved" in the orderportal. Each Bed Version are linked to one of these. 

These terms can be changed, but should be in an easy format for the customers and the change must be synced with:
- website
- orderportal
- orderform
- statusdb

Exceptions are TwistWESRefseq and TwistWholeExome. Could we (i.e. I) simply change the terms TwistWESRefseq and TwistWholeExome to TwistExomeRefseq and TwistExome for example @patrikgrenfeldt?

**Comment by hassanfa** [comment]
Alright, sounds good. What if we two versions of a bed file? Which one from Bed Version will be linked to it? The latest?

**Comment by annaengstrom** [comment]
If linkage is done when doing the order, there still needs to be an automatic fetch from LIMS which re-writes the information in statusdb as we might change bait set in the lab (we will in many cases forget to change any specific in statusdb while at the same time doing lab work, so it should be automatic). What has been done in the lab should be considered correct, and bed file should be based on the LIMS information. One thing we could consider is a solution where the order links the the latest version of a bait set to a sample, sends it to LIMS as a suggestion, and in case we change it in LIMS, the automatic update in statusdb from LIMS will take care of that information change, but I am not sure I like the idea. This is somewhat similar to the step in the lab where we choose indecies, we always decide in the lab, and all information regarding indecies is take from LIMS. 

We could possibly discuss more of course if anyone wants...

**Comment by henrikstranneheim** [comment]
Great work! Have you tested that the entire new procedure works both with MIP and Balsamic on a stage case for a representive bed?

**Comment by annaengstrom** [comment]
@henrikstranneheim @emmser I believe that in MIP production the bed files have the wrong names according to the new convention. Also, it seems in MIP you cannot tell which bed file to use, "Capture Kit" in statusdb does not indicate which file to use.

**Comment by hassanfa** [comment]
> Great work! Have you tested that the entire new procedure works both with MIP and Balsamic on a stage case for a representive bed?

Automation doesn't work for Balsamic, but now at least we have same filenames/bedfilenames across statusdb, lims, orderportal, and bioinfo reference data.

Feel free to add MIP bed files in `production/mip`, of course only for bedfiles in this repo.

**Comment by henrikstranneheim** [comment]
Ok, sounds good! I need to get a bit more up to speed on the new procedure, you are implementing. Do anyone of you have time for a short walk through on Monday so I can plan what I need to change? After operations meeting perhaps?

**Comment by hassanfa** [comment]
I can walk through the repo part on Monday.

**Comment by annaengstrom** [comment]
I think the major change for this compared to previously, is that before there were only one bed file for a "capture kit", since we always bought (a limited number of) off-the-shelf products from Agilent (SureSelect) and there were few options. Now, with very easy bait design and many cancer related projects, we have (many) versions (example "4.1") of bed files for (many) projects (example "4").

**Comment by patrikgrenfeldt** [comment]
> These are the names that the customers use for the actual order, these terms are available here: https://clinical.scilifelab.se/requirements and are "approved" in the orderportal. Each Bed Version are linked to one of these.
> 
> These terms can be changed, but should be in an easy format for the customers and the change must be synced with:
> 
>     * website
> 
>     * orderportal
> 
>     * orderform
> 
>     * statusdb
> 
> 
> Exceptions are TwistWESRefseq and TwistWholeExome. Could we (i.e. I) simply change the terms TwistWESRefseq and TwistWholeExome to TwistExomeRefseq and TwistExome for example @patrikgrenfeldt?

@annaengstrom If you change the bed.name in clinical-api and these are flagged as archived then I think nothing special will happen at all since the customers can't se archived beds. What is it that we want to achieve by changing the names of these?

**Comment by patrikgrenfeldt** [comment]
> Alright, sounds good. What if we two versions of a bed file? Which one from Bed Version will be linked to it? The latest?

@hassanfa @annaengstrom @keyvanelhami @emmser The new behaviour of cg (since cg.issue#535 & cg.PR#563) is to NOT link the samples to beds.

When cg is creating the config for starting Balsamic it 
1. contacts Lims to find the actual "bait set" in that was used in the lab. 
1. With the actual "bait set" it queries the clinical-api.bed-version to find a match on the "shortname"
1. The filename on the bed-version is used in the Balsamic-config (unless the user overruled by using the -p flag)

Questions or concerns?

**Comment by hassanfa** [comment]
> > Alright, sounds good. What if we two versions of a bed file? Which one from Bed Version will be linked to it? The latest?
> 
> @hassanfa @annaengstrom @keyvanelhami @emmser The new behaviour of cg (since cg.issue#535 & cg.PR#563) is to NOT link the samples to beds.
> 
> When cg is creating the config for starting Balsamic it
> 
> 1. contacts Lims to find the actual "bait set" in that was used in the lab.
> 2. With the actual "bait set" it queries the clinical-api.bed-version to find a match on the "shortname"
> 3. The filename on the bed-version is used in the Balsamic-config (unless the user overruled by using the -p flag)
> 
> Questions or concerns?

That is clear.

Question about reruns: if there is an analysis rerun for an older version of bait set, will it also work?

**Comment by annaengstrom** [comment]
> 
> That is clear.
> 
> Question about reruns: if there is an analysis rerun for an older version of bait set, will it also work?

I think I might need to add new "short names" in clinical-api that matches exactly what has been previously been used in LIMS (I will link to the correct bed files), so that re-runs are possible. What are your thoughts on this?

**Comment by annaengstrom** [comment]
> > I am still confused why would MIP need small panels (since rare diseases go on WGS anyway), but why not.
> 
> Some rare disease cases will be analysed using panels (exoms or even smaller panels such as GMCK Solid) because the referring clinic does not want to take the cost of WGS. We have some patient categories where this will be standard, eg cardio and hearing loss.

This seems to be linked to the problems in PROD#71 and PROD#115 (AM docs), do we have a plan for a solution?

- PROD#71: PAN cases contains no sv variants due to it being a small panel sample and this makes storing and uploading of the case very difficult

- PROD#115: Handling PAN cases in MIP Updated

**Comment by patrikgrenfeldt** [comment]
> I think I might need to add new "short names" in clinical-api that matches exactly what has been previously been used in LIMS (I will link to the correct bed files), so that re-runs are possible. What are your thoughts on this?

Yes I think that is exactly what we need

**Comment by hassanfa** [comment]
> > > I am still confused why would MIP need small panels (since rare diseases go on WGS anyway), but why not.
> > 
> > 
> > Some rare disease cases will be analysed using panels (exoms or even smaller panels such as GMCK Solid) because the referring clinic does not want to take the cost of WGS. We have some patient categories where this will be standard, eg cardio and hearing loss.
> 
> This seems to be linked to the problems in PROD#71 and PROD#115 (AM docs), do we have a plan for a solution?
> 
> * PROD#71: PAN cases contains no sv variants due to it being a small panel sample and this makes storing and uploading of the case very difficult
> * PROD#115: Handling PAN cases in MIP Updated

This is a workflow issue for MIP and it should be handled on that front. I'm afraid it is not related to this repository and it can't be addressed here.

**Comment by annaengstrom** [comment]
Statusdb is now updated with all "shortnames" that have been used in LIMS so far. The correct bedfile is linked to each shortname.

**Comment by hassanfa** [comment]
This is done. Closing it. Further task should be covered in other/new issues.
