### ISSUE TITLE
Latest directory with latest version or softlink

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#29]
There will be multiple bedfiles, but we are mostly interested in latest version. Should keep track of older version, and not remove them from this repo.

**Comment by vwirta** [comment]
My spontaneous feeling is that we should keep the old versions as well. 
There will a lot of data prepared using old versions.
And I do not think we will have too many versions of each panel... unlikely that there will be more than 1-2 updates per year.

**Comment by hassanfa** [comment]
We already keep multiple bed files through versions in files. Old files will stay alive!
