### ISSUE TITLE
Create entry for Twist Comprehensive Exome Panel

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#41]
Content TBD.

More info here: https://www.twistbioscience.com/resources/twist-comprehensive-exome

- [x] Add bed file
- [x] Add to README
- [x] Create UCSC track

**Comment by annaengstrom** [comment]
Did we ever get the bed file for Comprehensive?

**Comment by hassanfa** [comment]
I don't think so. Did they send it by email? Cause there is nothing on their website.

**Comment by annaengstrom** [comment]
It is supposedly the same bed file as Core Exome + RefSeq, still it would be interesting to compare with the one we have I guess? Seems that the baits though are the same.

**Comment by hassanfa** [comment]
I vaguely remember it is not just merge of those two. I'll look into this.
