### ISSUE TITLE
Fill out annotation detail for GMCKSolid panel

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#42]
@keyvanelhami Now that two workflows are merged, lets add these annotations (gene count, snp count, etc) for a single panel and fill out that table: https://github.com/Clinical-Genomics/target_capture_bed#CG4.1

The procedure is to:
- [x] Run the workflow you have created on the GMCKSolid panel
- [x] Write required scripts to count annotations and features for table: https://github.com/Clinical-Genomics/target_capture_bed#CG4.1
~- [ ] Annotated file should be placed in `production/annotation`~
- [x] Scripts (or even if you use ipython or jupyter notebooks) should be placed in `utilities`
- [x] Script input: gmcksolid_4.1_hg19_design.bed output1: gmcksolid_4.1_hg19_design.annotated.bed output2: Gene count, unique transcript count, dbsnp count, cosmic snp count.

Annotated output can be multiple files or single files, it's your call whichever you choose.

**Comment by keyvanelhami** [comment]
Look at pandas report table for the last step.

**Comment by hassanfa** [comment]
This is done!
