### ISSUE TITLE
Annotate Lymphomatic as a validation and test dataset

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/target_capture_bed#46]
- [x] Annotate lymphomatic with dbSNP (vXXX)
- [x] Annotate lymphomatic with COSMIC (vXXX)
- [x] Annotate lymphomatic with gene, transcript, and exon information (source refFlat)
- [x] Manually check if all regions in lymphomatic bed-file have been annotated.
- [x] Validate each of the 43 entries in annotated bed files using UCSC genome track †
- [ ] Find a way to add this to travis if possible

----------
† Annotation validation for COSMIC might not be possible using UCSC track since COSMIC might not be a public track

**Comment by keyvanelhami** [comment]
- [x] Annotate lymphomatic with gene, transcript, and exon information (source refflat)

1. Change the name of the bed-file in line 10 in the `snakefile` in `target_capture_bed/utilities/gene_annotation` to `"lymphomatic_2.1_hg19_design"`
2. Run above snakefile

![Screen Shot 2020-04-07 at 1 46 17 PM](https://user-images.githubusercontent.com/26735714/78665432-18a4a800-78d6-11ea-8eaf-b327d4de0752.png)


![Screen Shot 2020-04-07 at 1 37 20 PM](https://user-images.githubusercontent.com/26735714/78664738-e6df1180-78d4-11ea-8df2-e3fc615f86a5.png)

**Comment by hassanfa** [comment]
We also discussed that you manually went through all the regions, and verified that they are correctly annotated. Right?

**Comment by keyvanelhami** [comment]
> We also discussed that you manually went through all the regions, and verified that they are correctly annotated. Right?

Yes, I have done that and all of them were correct annotated. I will add a bullet point and add the results

**Comment by keyvanelhami** [comment]
@hassanfa All bullet points are now done, and the only one left is the travis one. Should we discuss this together?

**Comment by hassanfa** [comment]
travis needs to use dbsnp and refflat files to make it work.

It'd be better to make a PR for these developments that you've done, merge it into master. It'll be a quick one (since you've done all of the tests).

**Comment by keyvanelhami** [comment]
@hassanfa I am looking into my old branch "fill_bed_table". Is this issue done now by adding it to travis?

**Comment by hassanfa** [comment]
I actually looked into adding big ref files as cache files to travis, and it seems to be quite tricky in the long run (more maintenance ). We can close this issue, and look for alternative way of testing the code with a real dataset.

Will you do the honor of closing this, or should I do it?

**Comment by hassanfa** [comment]
by the way, well done on finishing this :-)

**Comment by keyvanelhami** [comment]
I take the honor to close it :)
